### ISSUE TITLE
Modern CSS problem

### ISSUE THREAD

**Issue by Frohus** [django-compressor/django-compressor#1288]
I've encountered an issue while upgrading from Tailwind 3 to 4 and DaisyUI 4 to 5. The compressor is breaking the output CSS file containing modern selectors. There are no errors during compression; I learned about it the hard way after deploying it to production.  I'm using the default config with offline compression.

```css
:is(input[type=url],input[type=text],input[type=number],input[type=email],input[type=password],input[type=tel],input[type=date]):where(input) {
    display: inline-flex
}
```
Becomes (missing closing bracket after `url`) and breaks the rest of the rules in file
```css
:is(input[type=url,input[type=text],input[type=number],input[type=email],input[type=password],input[type=tel],input[type=date]):where(input) {
    display: inline-flex
}
```
